# AppVeyor Configuration
# Adapted from https://packaging.python.org/en/latest/appveyor/

environment:
  # Specify environment variables for setting up the build process
  matrix:
    # Define Python version and tox environment to use for testing
    # For a list of supported Python versions on AppVeyor, refer to:
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Python37-x64"
      TOXENV: py37

matrix:
  # Allow failures for Python 3.7 installation, since AppVeyor doesn't install it yet
  allow_failures:
    - PYTHON: "C:\\Python37-x64"
      # Appveyor does not yet install python-3.7 by default

install:
  # Install dependencies before running tests
  - |
    %PYTHON%\python.exe -m pip install wheel tox

# Explanation:
# %PYTHON% refers to the selected Python interpreter (e.g., python.exe).
# %PYTHON%\Scripts contains pip.exe, tox.exe, and other executables installed by pip.

build: off  # Disable automatic build step

test_script:
  # Custom test script to run tox with the selected Python version
  # Make sure to reference the correct path to tox using %PYTHON%\Scripts\tox.exe
  - |
    misc\windows-build.cmd %PYTHON%\Scripts\tox.exe

after_test:
  # This section is used for any post-test steps (e.g., wheel building)
  # Build the wheels or perform other tasks after tests have passed
  # If building C extensions for 64-bit Python 3.3/3.4, use build.cmd
  # Use %PYTHON% to ensure you're using the correct Python interpreter
  - |
    misc\windows-build.cmd %PYTHON%\Scripts\tox.exe
